#!/bin/bash

#################################################
#                                               #
#    Bash script for Arch Linux installation    #
#                                               #
#    Run script as following:                   #
#    create_symlinks GIT_USERNAME GIT_EMAIL     #
#                                               #
#################################################

# Check that there are two parameters
if [[ $# -lt 2 ]] ; then
    echo "Run program as:"
    echo "create_symlinks GIT_USERNAME GIT_EMAIL"
    exit 0
fi

GIT_NAME=$1
GIT_EMAIL=$2
COMMON_FILES=".bash_profile .bashrc .tmux.conf .vim .vimrc .zshrc"
I3_FILES=".config .Xdefaults .xinitrc .Xmodmap .Xresources"
ABS_PATH="/home/$(whoami)"

# Utilities
# bind-tools - dig command
# xclip - rxvt clipboard interaction
# xsel - perl script
# python2-sip, python2-pyqt4 and lib32-mpg123 - dependencies for fightcade
# scrot - Screenshot
IMPORTANT="vim tmux dmenu gedit firefox htop evince thunar unzip mpv feh scrot rxvt-unicode"
GRAPHICAL="mesa xorg xorg-twm xorg-xinit"
I3="i3 i3blocks"
AUDIO="alsa-utils pulseaudio pulseaudio-alsa lib32-alsa-plugins lib32-libpulse"
OTHER="cmake openssh keychain lxappearance bind-tools xclip xautolock lm_sensors xsel lib32-mpg123"
PYTHON="python python-virtualenv python-virtualenvwrapper python2-sip python2-pyqt4"
FONTS="ttf-hack ttf-dejavu ttf-liberation adobe-source-han-sans-otc-fonts"

# CHECK IF NEEDED?
# Runs a background process that runs a program as super user so
# that the sudo password can be saved
# From: https://github.com/mathiasbynens/dotfiles/blob/master/.osx
# sudo -v
# while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "Installing must-have programs"
sudo pacman -S $IMPORTANT $GRAPHICAL $I3 $AUDIO $OTHER $PYTHON $FONTS
echo "...done"

echo "Configure git username and email"
git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"
echo "...done"

echo "Generate ssh keys"
ssh-keygen -t rsa -b 4096 -C "$GIT_EMAIL"
if test $(ssh-agent -s); then
    ssh-add ~/.ssh/id_rsa
fi
echo "...done"

echo "Add your public key to your github account(s)"
echo "Press RETURN to continue..."
read nothing

echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
echo "...done"

echo "Creating symlinks"
for f in $COMMON_FILES
do
    ln -sf ~/.dotfiles/files/$f ~/$f
done
for f in $I3_FILES
do
    ln -sf ~/.dotfiles/i3files/$f ~/$f
done
ln -sf ~/.dotfiles/.fonts ~/.fonts
echo "...done"

echo "Creating symbolic link for copy and paste"
sudo ln -s $ABS_PATH/.dotfiles/archscripts/clipboard /usr/lib/urxvt/perl/clipboard
echo "...done"

echo "Installing Vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo "...done"

echo ""
echo "FINISHED"
