# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2892e3b2-a4b9-4e7b-9a53-9e4083fab569";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/19A9-1306";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/899fc538-d406-4789-9db3-84dfe35613d9"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
