#!/bin/bash

# TODO: Make it mirror on all connected screens

OUTPUT=$1
LAPTOP="LVDS1"

# Get the largest common resolution
RESOLUTIONS=$(xrandr | grep '^[ ]*[0-9]' | awk '{print $1}' | sort | uniq -d)
LARGEST=0

for r in $RESOLUTIONS ; do
    PROD=$(echo $r | sed "s/x/*/" | bc)
    if [[ $PROD -gt $LARGEST ]] ; then
        LARGEST=$PROD
        LARGEST_RES=$r
    fi
done

if [[ -n $LARGEST_RES ]] ; then
    xrandr --output $LAPTOP --mode $LARGEST_RES --output $OUTPUT --mode $LARGEST_RES
fi

exit
