#!/bin/bash
# Updates all packages and removes orphans

echo ":: updating system..."
sudo pacman -Syu
echo "...done"

echo ":: Removing orphans..."
sudo pacman -Rns $(pacman -Qtdq)
echo "...done"
exit
