[language-server.expert]
command = "expert"

[language-server.tailwindcss-ls]
args    = ["--stdio"]
command = "tailwindcss-language-server"

[language-server.vscode-css-language-server]
args                       = ["--stdio"]
command                    = "vscode-css-language-server"
config.css.validate.enable = true
config.provideFormatter    = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "typescript"]}
file-types = ["tsx", "ts"]
auto-format = true

[[language]]
name = "elixir"
auto-format = true
language-servers = ["expert"]

[[language]]
name = "heex"
auto-format = true
language-servers = ["elixir-ls", "expert"]

# [[language]]
# name = "elixir"
# scope = "source.elixir"
# injection-regex = "(elixir|ex)"
# file-types = ["ex", "exs", { glob = "mix.lock" }]
# shebangs = ["elixir"]
# roots = ["mix.exs", "mix.lock"]
# comment-token = "#"
# language-servers = [ "elixir-ls", "expert" ]
# indent = { tab-width = 2, unit = "  " }
# auto-format = true

# [[language]]
# name = "heex"
# scope = "source.heex"
# injection-regex = "heex"
# file-types = ["heex"]
# roots = ["mix.exs", "mix.lock"]
# block-comment-tokens = { start = "<!--", end = "-->" }
# indent = { tab-width = 2, unit = "  " }
# language-servers = [ "elixir-ls", "expert" ]
# auto-format = true

